# Generated by Django 4.1.4 on 2022-12-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
